project:
  type: book
  output-dir: _book

book:
  title: "Options and VaR with R"
  subtitle: "Book"
  author: "Dr. Martin Lozano"
  page-navigation: true
  search: true
  date: today
  date-format: "MMMM D, YYYY"
  sidebar:
    style: docked
    collapse-level: 1
  page-footer:
    left: "Options and VaR with R"
    right: 'Dr. Martin Lozano &middot; <a href="mailto:mlozanoqf@gmail.com">mlozanoqf@gmail.com</a> &middot; <a href="https://mlozanoqf.github.io/">mlozanoqf.github.io</a>'
  chapters:
    - text: "Options and VaR with R"
      href: index.qmd
    - 01-payoff-functions.qmd
    - 02-options-properties.qmd
    - 03-wiener-processes.qmd
    - 04-value-at-risk.qmd
    - references.qmd

bibliography: references.bib
link-citations: true

crossref:
  chapters: true

execute:
  freeze: auto
  warning: false
  message: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: false
    toc-title: "On this page"
    toc-location: right
    toc-depth: 2
    smooth-scroll: true
    code-fold: true
    code-copy: true
    code-tools:
      toggle: true
      source: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    number-sections: true
    number-depth: 3
    page-layout: full
    include-after-body:
      - analytics_if.html
      - back-to-top.html
      - progressbar.html
      - sidebar-toggle.html
      - local-navigation.html
      - page-sections.html
      - sidebar-accordion.html
      - sidebar-chapter-sections.html
    css: styles.css
