---
title: Options and VaR with `r fontawesome::fa("r-project")` <span style="color:white">R</span>

subtitle: Dr. Martín Lozano.
author:
#- name: Back to main [`r fontawesome::fa("home")`](https://mlozanoqf.github.io/)
#  affiliation: Academic website. [Web.](https://sites.google.com/site/mlozanoqf/)
date: Current `r fontawesome::fa("code-commit") ` `r format(Sys.time(), '%d %b %Y, %H:%M:%S.')`
#  bookdown::gitbook: default
output: 
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    fig_caption: yes
    code_folding: hide
    theme: readable #darkly 
    includes:
      after_body: analytics_if.html
abstract: This material relies on John C. Hull [@Hull]. Some mathematical background is skipped to emphasize the data analysis, model logic, discussion, graphical approach and R coding [@Rref]. As in the philosophy of Donald Knuth [@knuth1984literate], the objective of this document is to explain to human beings what we want a computer to do as literate programming. This is a work in progress and it is under revision.
bibliography: references.bib
link-citations: yes
---

```{=tex}
\newpage 
\hypersetup{linkcolor=black}
\renewcommand*\contentsname{Index.}
\tableofcontents
```

```{r include=FALSE}
# This removes all items in environment. 
# It is a good practice to start your code this way.
rm(list=ls())
library(fontawesome)
library(tictoc)
tic()
```

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

```{r, xaringanExtra-clipboard, echo=FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clone fa-2x\" style=\"color: #301e64\"></i>",
    success_text = "<i class=\"fa fa-check fa-2x\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times fa-2x\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

````{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('contact.html')
```
````

# [`r fa("arrow-circle-left", fill = "black")`](https://mlozanoqf.github.io/) [<span style="color: black">Back to QFR.</span>](https://mlozanoqf.github.io/) {-}

# [`r fa("arrow-circle-up", fill = "black")`](https://mlozanoqf.github.io/tutorial_if/) [<span style="color: black">Back to top.</span>](https://mlozanoqf.github.io/tutorial_if/) {-}

\newpage

```{r strategies, child = 'strategies.Rmd'}
```

\newpage

```{r valuation, child = 'valuation.Rmd'}
```

\newpage

```{r wiener, child = 'wiener.Rmd'}
```

\newpage

```{r VaR, child = 'VaR.Rmd'}
```

```{r include=FALSE}
a <- toc()
```

This document took `r round(as.numeric((a$toc-a$tic)/60), 2)` minutes to compile in Rmarkdown, `r R.version.string`.

# References.


