{
  "hash": "ae6b79b2a8ea9a724464f406e071b825",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n\n\n# Wiener processes\n\nHere we review stochastic process that are useful in finance, especially in the Black-Scholes context. This section is based on @Hull, chapter 14.\n\n## The basic process\n\nA simple Wiener process.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A typical Wiener process.\nTT <- 5\nN <- 10000\ndt <- TT / N\nTime <- seq(from = dt, to = TT, by = dt)\nset.seed(560746) # for reproducibility purposes.\ndelta_z <- rnorm(N, 0, 1) * dt^0.5 \nz <- 25 + cumsum(delta_z) # The initial price is 25.\n```\n:::\n\n\n\n\nGraphically:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Time, z, type = \"l\",\n     ylab = \"z in the texbook, it could be a stock price\",\n     xlab = \"Time\")\nlines(Time, seq(25, (25 + sum(delta_z)), length.out = N), lty = 2,\n      col = \"purple\")\npoints(Time[1], 25, col = \"blue\", cex = 2, pch = 16)\npoints(Time[N], z[N], col = \"red\", cex = 2, pch = 16)\nlegend(\"topleft\", legend = c(round(z[N], 2)), bg = \"white\", \n       text.col = \"red\")\n```\n\n::: {.cell-output-display}\n![Wiener process 10,000 steps from blue $z(0)=25$ to $z(T)=26.2$ in red.](03-wiener-processes_files/figure-html/fig-wp1sfbtir-1.png){#fig-wp1sfbtir width=672}\n:::\n:::\n\n\n\nThis is a 1,000 step version of four Wiener processes:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/X-VRWeqG_I8\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/X-VRWeqG_I8\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThis is supposed to mimic (at some extent) the evolution of a stock price. \n\nNow, we propose to produce 100 processes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 100 Wiener processes.\nset.seed(365633)\nmat.delta_z <- matrix(rnorm(100 * N, mean = 0, sd = 1) * sqrt(dt), 100, N) \nmat.z1 <- 25 + t(apply(mat.delta_z, 1, cumsum)) \nmat.z <- t(cbind(matrix(25, 100), mat.z1))\nTime2 <- c(0, Time)\npred <- mean(mat.z[(N + 1), ])\n# 95% range.\nrangetop <- pred + qnorm(0.975) * var(mat.z[(N + 1), ])^0.5\nrangedown <- pred - qnorm(0.975) * var(mat.z[(N + 1), ])^0.5\n```\n:::\n\n\n\n\nGraphically.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatplot(Time2, mat.z, type = \"l\", lty = 1, col = rgb(0, 0, 1, 0.3),\n     ylab = \"z in the textbook, it could be a stock price\",\n     xlab = \"Time\")\nabline(h = pred, lty = 2, col = \"red\")\nabline(v = 0, lty = 2)\nlines(Time2, seq(25, pred, length.out = N + 1), lty = 2)\npoints(Time2[N + 1], pred, col = \"red\", cex = 2, pch = 16)\npoints(0, 25, col = \"black\", cex = 2, pch = 16)\nlegend(\"topleft\", legend = c(round(pred, 2)), bg = \"white\", \n       text.col = \"red\")\nabline(h = rangetop, lty = 2)\nabline(h = rangedown, lty = 2)\n```\n\n::: {.cell-output-display}\n![100 Wiener process 10,000 steps, initial price at 25, red is the mean at $T$.](03-wiener-processes_files/figure-html/fig-owp1sipa2ritmat-1.png){#fig-owp1sipa2ritmat width=672}\n:::\n:::\n\n\n\n\nLet's check how many simulated terminal values fall outside this 95% prediction range.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(mat.z[(N + 1), ] > rangetop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(mat.z[(N + 1), ] < rangedown)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\n\nThis means that 5 paths are outside this simulated 95% prediction range.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mat.z[(N + 1), ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  20.97   23.79   24.96   25.02   26.06   31.38 \n```\n\n\n:::\n:::\n\n\n\n\nA potential problem is that $z$ values can be negative. This is problematic when we are interested to model stock prices.\n\nLet's explore deeper the stochastic process below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ndelta_z <- rnorm(N, 0, 1) * dt^0.5 \nz <- 25 + cumsum(delta_z)\n### A stochastic process\npar(mfrow = c(2, 2), mai = c(0.4, 0.4, 0.4, 0.4))\npar(pty = \"s\")\nplot(Time, z, type = \"l\", xlim = c(0, TT), ylim = c(22.5, 26),\n     main = \"Full 5-year period\", ylab = \"z\", xlab = \"Time\")\nplot(Time, delta_z, type = \"h\", xlim = c(0, TT),\n     main = \"Full 5-year period\", \n     ylab = expression(paste(Delta,z)), xlab = \"Time\")\nabline(h = 0, lty = 2, col = \"orange\", lwd = 2)\nplot(Time, z, type = \"l\", xlim = c(0, 1/12), ylim = c(24.9, 25.35),\n     main = \"Zoom: first month only\", xlab = \"Time\")\nplot(Time, delta_z, type = \"h\", xlim = c(0, 1/12), \n     col = ifelse(delta_z < 0, \"red\", \"blue\"), ylim = c(-0.055, 0.055),\n     main = \"Zoom: first month only\", \n     ylab = expression(paste(Delta,z)), xlab = \"Time\")\n```\n\n::: {.cell-output-display}\n![A stochastic process with zoom.](03-wiener-processes_files/figure-html/fig-aspwz-1.png){#fig-aspwz width=672}\n:::\n:::\n\n\n\n\nThese processes are driven by a random component. The lower panel is revealing because we can see how the random component goes from positive to negative without any pattern, it is entirely random. Now, let's explore the role of $\\Delta t$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), mai = c(0.4, 0.4, 0.4, 0.4))\npar(pty = \"s\")\nplot(Time[(seq(from = 1, to = N, length.out = 10))],\n     z[(seq(from = 1, to = N, length.out = 10))], type = \"l\",\n     ylim = c(22.5, 26), main = expression(paste(\"Large \",Delta,t)),\n     ylab = \"z\")\nabline(v = 0, lty = 2)\nabline(v = 5, lty = 2)\nplot(Time[(seq(from = 1, to = N, length.out = 100))],\n     z[(seq(from = 1, to = N, length.out = 100))], type = \"l\", \n     ylim = c(22.5, 26), ylab = \"z\", \n     main = expression(paste(\"Small \",Delta,t)))\nabline(v = 0, lty = 2)\nabline(v = 5 , lty = 2)\nplot(Time[(seq(from = 1, to = N, length.out = 1000))],\n     z[(seq(from = 1, to = N, length.out = 1000))], type = \"l\", \n     ylim = c(22.5, 26), ylab = \"z\", \n     main = expression(paste(\"Even smaller \",Delta,t)))\nabline(v = 0, lty = 2)\nabline(v = 5 , lty = 2)\nplot(Time, z, type = \"l\", ylim = c(22.5, 26), # length 10,000\n     main = expression(paste(\"True process \",Delta,t, \" \",\n                             \"tends \",\"to \",\"zero\")))\nabline(v = 0, lty = 2)\nabline(v = 5, lty = 2)\n```\n\n::: {.cell-output-display}\n![Wiener process, the role of $\\Delta t$.](03-wiener-processes_files/figure-html/fig-wptrod-1.png){#fig-wptrod width=672}\n:::\n:::\n\n\n\n\nThe $\\Delta t$ value determines how frequent are the changes in $z$.\n\nA few properties of stochastic processes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(delta_z) # should be zero\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.0001461726\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(delta_z)^0.5 # should be dt^.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02263698\n```\n\n\n:::\n\n```{.r .cell-code}\ndt^0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02236068\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(delta_z) # should be dt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0005124328\n```\n\n\n:::\n\n```{.r .cell-code}\ndt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5e-04\n```\n\n\n:::\n:::\n\n\n\n\n## The generalized Wiener process\n\nNow let's analyze the case of the generalized Wiener process.\n\n$\\Delta x = a \\Delta t + b \\epsilon \\sqrt{\\Delta t}$. Assume $a=0.3$ and $b=1.5$:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Figure 14.2\nTT <- 50\nN <- 200\ndt <- TT / N\nTime <- seq(from = 0, to = TT, by = dt)\nset.seed(123)\ndelta_z <- 1.5 * rnorm(N, 0, 1) * dt^0.5\ndelta_x <- (0.3 * dt) + delta_z\nx <- c(0, cumsum(delta_x))\nz <- c(0, cumsum(delta_z))\n```\n:::\n\n\n\n\nGraphically:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Time, x, type = \"l\", lwd = 4, ylim = c(-7, 22))\nlines(Time, z, col = \"red\", lwd = 4)\nlines(Time, 0.3 * Time, col = \"blue\", lwd = 4)\nabline(0, 0)\nabline(v = 0)\nlegend(\"topleft\", legend = c(\"Generalized Wiener process\", \n                             \"Drift\", \"Stochastic component\"),\n       col = c(\"black\", \"blue\", \"red\"), lwd = 3, \n       bg = \"white\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![Generalized Wiener process.](03-wiener-processes_files/figure-html/fig-gwp-1.png){#fig-gwp width=672}\n:::\n:::\n\n\n\nHere, the generalized Wiener process $\\Delta x$ is decomposed into the drift $a \\Delta t$ and the stochastic component $b \\epsilon \\sqrt{\\Delta t}$. A zoom of the same plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Figure 14.2 Zoom\nplot(Time, x, type = \"b\", ylim = c(-0.6, 1), xlim = c(0, 1), lwd = 4)\nlines(Time, z, col = \"red\", lwd = 4, type = \"b\")\nlines(Time, 0.3 * Time, col = \"blue\", lwd = 4, type = \"b\")\nabline(0, 0)\nabline(v = 0)\nabline(v = dt, lty = 2)\nabline(v = dt * 2, lty = 2)\nabline(v = dt * 3, lty = 2)\nabline(v = dt * 4, lty = 2)\n#points(dt, 0, pch = 1, col = \"blue\", lwd = 2)\n#points(dt * 2, 0, pch = 1, col = \"blue\", lwd = 2)\n#points(dt * 3, 0, pch = 1, col = \"blue\", lwd = 2)\n#points(dt * 4, 0, pch = 1, col = \"blue\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Generalized Wiener process\", \n                           \"Drift\", \"Stochastic component\"),\n       col = c(\"black\", \"blue\", \"red\"), lty = 1, \n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Generalized Wiener process, zoom view.](03-wiener-processes_files/figure-html/fig-gwpzv-1.png){#fig-gwpzv width=672}\n:::\n:::\n\n\n\n\nThis is a nice visual representation of: generalized = drift + Wiener.\n\nSee how the process changes when we consider a lower value of $a$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ndelta_xlow <- (0.15 * dt) + delta_z\nxlow <- c(0, cumsum(delta_xlow))\n# Now plot.\nplot(Time, xlow, type = \"l\", ylim = c(-7, 22), lwd = 4, ylab = \"x\")\nlines(Time, x, lwd = 2, col = \"grey\")\nlines(Time, z, lwd = 4, col = \"red\")\nlines(Time, 0.15 * Time, lwd = 4, col = \"blue\")\nlines(Time, 0.3 * Time, lty = 2, lwd = 2, col = \"grey\")\nabline(0, 0)\nabline(v = 0)\nlegend(\"topleft\", legend = c(\"Original generalized Wiener process\", \n    \"Original drift\", \"New generalized Wiener process\", \"New drift\",\n    \"Stochastic component\"), lty = c(1, 2, 1, 1, 1), \n    bg = \"white\", lwd = 2,\n    col = c(\"grey\", \"grey\", \"black\", \"blue\", \"red\"), cex = 0.85)\n```\n\n::: {.cell-output-display}\n![Generalized Wiener process, lower a.](03-wiener-processes_files/figure-html/fig-gwpla-1.png){#fig-gwpla width=672}\n:::\n:::\n\n\n\n\nAnd a higher value of $b$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ndelta_zhigh <- 3 * rnorm(N, 0, 1) * dt^0.5\ndelta_xhigh <- (0.3 * dt) + delta_zhigh\nxhigh <- c(0, cumsum(delta_xhigh))\nzhigh <- c(0, cumsum(delta_zhigh))\nplot(Time, xhigh, type = \"l\", ylim = c(-7, 22), lwd = 4, ylab = \"x\")\nlines(Time, x, lwd = 2, col = \"grey\")\nlines(Time, zhigh, lwd = 4, col = \"red\")\nlines(Time, z, lwd = 2, col = \"grey\")\nlines(Time, 0.3 * Time, lwd = 4, col = \"blue\")\nabline(0, 0)\nabline(v = 0)\nlegend(\"topleft\", legend = c(\"New generalized Wiener process\", \n      \"Original generalized Wiener process\", \"Drift\" ,\n      \"New stochastic component\", \"Original stochastic component\"), \n      lty = 1, bg = \"white\", lwd = 2,\n      col = c(\"black\", \"grey\", \"blue\", \"red\", \"grey\"), cex = 0.75)\n```\n\n::: {.cell-output-display}\n![Generalized Wiener process, higher b.](03-wiener-processes_files/figure-html/fig-gwphb-1.png){#fig-gwphb width=672}\n:::\n:::\n\n\n\n\nNote the changes are now more pronounced.\n\nThis is a replication of @Hull, table 14.1. Simulation of stock price when $\\mu= 0.15$ and $\\sigma = 0.30$ during 1-week periods.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Table 14.1\nset.seed(19256)\ndelta_S <- rep(0, 10)\nS <- rep(100, 10)\nepsilon <- rep(0, 10)\nfor(i in 1:10){\n  epsilon[i] <- rnorm(1, 0, 1)\n  delta_S[i] <- 0.15 * (1 / 52) * S[i] + 0.3 * ((1 / 52)^0.5) * \n    epsilon[i] * S[i]\n  S[i+1] <- S[i] + delta_S[i]\n}\nepsilon <- c(epsilon, NA)\ndelta_S <- c(delta_S, NA)\nresults <- data.frame(S, epsilon, delta_S)\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          S    epsilon    delta_S\n1  100.0000  0.8268625  3.7284174\n2  103.7284  0.4957988  2.4387684\n3  106.1672 -0.9313823 -3.8074983\n4  102.3597 -0.1495925 -0.3417592\n5  102.0179  0.7310239  3.3968957\n6  105.4148 -0.6111472 -2.3761181\n7  103.0387  1.2490868  5.6516490\n8  108.6904 -0.6243389 -2.5096009\n9  106.1808  0.6995349  3.3964067\n10 109.5772  0.3612549  1.9629353\n11 111.5401         NA         NA\n```\n\n\n:::\n:::\n\n\n\n\nIt is interesting to note that in @Hull the final simulated price is \\$111.54 and here it is \\$111.5401. Is this a pure coincidence?\n\nA correlated process.\n\n$\\Delta x_1 = a_1 \\Delta t + b_1 \\epsilon_1 \\sqrt{\\Delta t}$,\n\n$\\Delta x_2 = a_2 \\Delta t + b_2 \\epsilon_2 \\sqrt{\\Delta t}$.\n\nWhere: $\\epsilon_1 = u$, and $\\epsilon_2=\\rho u + \\sqrt{1-\\rho^{2}}v$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Section 14.5\nrho <- 0.8\nTT <- 1\nsteps <- 1000\ndt <- TT / steps\nTime <- seq(from = dt, to = TT, by = dt)\nset.seed(123)\ne1 <- rnorm(steps, 0, 1)\ne2 <- rho * e1 + ((1 - rho^2)^0.5) * rnorm(steps, 0, 1)\ndelta_z1 <- 1.5 * e1 * dt^0.5\ndelta_z2 <- 1.5 * e2 * dt^0.5\ndelta_x1 <- (0.3 * dt) + delta_z1\ndelta_x2 <- (0.3 * dt) + delta_z2\nx1 <- cumsum(delta_x1)\nx2 <- cumsum(delta_x2)\nx <- c(x1, x2)\n```\n:::\n\n\n\n\nAssume $a=0.3$, $b=1.5$ and $\\rho=0.8$. Visually:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Time, x1, type = \"l\", ylim = c(min(x), max(x)), ylab = \"x1 and x2\")\nlines(Time, x2, col = \"red\")\nabline(0, 0)\n```\n\n::: {.cell-output-display}\n![Correlated processes x1 and x2.](03-wiener-processes_files/figure-html/fig-cpxax-1.png){#fig-cpxax width=672}\n:::\n:::\n\n\n\n\n<!-- The following code needs revision. -->\n\n<!-- ```{r fig.cap=\"ItÃ´ process. This figure needs revision.\"} -->\n<!-- # Figure 14.2 with ItÃ´ process -->\n<!-- TT <- 50 -->\n<!-- N <- 200 -->\n<!-- dt <- TT / N -->\n<!-- Time <- seq(from = 0, to = TT, by = dt) -->\n<!-- set.seed(1) -->\n<!-- axt <- 0.3 + rnorm(N + 1, 0, 1) * 0.001 * Time -->\n<!-- bxt <- 0.001 * Time + 0.1 -->\n<!-- delta_z <- bxt * rnorm(N + 1, 0, 1) * dt^0.5 -->\n<!-- delta_x <- (axt * dt) + delta_z -->\n<!-- xI <- cumsum(delta_x) -->\n<!-- zI <- cumsum(delta_z) -->\n<!-- # Now plot. -->\n<!-- plot(Time, xI, type = \"l\", lwd = 2, ylim = c(0, 18), ylab = \"x\") -->\n<!-- lines(Time, zI, col = \"red\", lwd = 2) -->\n<!-- lines(Time, axt * Time, col = \"blue\", lwd = 2) -->\n<!-- abline(0, 0) -->\n<!-- abline(v = 0) -->\n<!-- legend(\"topleft\", legend = c(\"ItÃ´ process\",  -->\n<!--                            \"Stochastic drift\", \"Wiener process\"), -->\n<!--        col = c(\"black\", \"blue\", \"red\"), lty = 1, bg = \"white\", lwd = 2) -->\n<!-- ``` -->\n\n<!-- This is a clear view of a typical ItÃ´ process. Taken from Esteban Moro. -->\n\n<!-- ```{r echo=FALSE, out.width='50%', fig.align=\"center\", fig.cap=\"ItÃ´ process.\"} -->\n<!-- knitr::include_graphics('./pdf1.jpg') -->\n<!-- ``` -->\n\nThe model of stock price behavior implies that a stock's price at time $T$, given its price today, is lognormally distributed. The following is similar to example 15.1 in @Hull. In particular, consider a stock with an initial price of \\$40, an expected return of 16% per annum, and a volatility of 20% per annum. \n\n$\\frac{\\Delta S}{S} = a \\Delta t + b \\epsilon \\sqrt{\\Delta t}$,\n\n$\\frac{\\Delta S}{S} = 0.16 \\Delta t + 0.2 \\epsilon \\sqrt{\\Delta t}$,\n\nAssume $\\Delta t = \\frac{1}{365}$: $\\frac{\\Delta S}{S} = 0.16 \\frac{1}{365} + 0.2 \\epsilon \\sqrt{\\frac{1}{365}}$,\n\nCalculate the constants:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.16/365\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0004383562\n```\n\n\n:::\n\n```{.r .cell-code}\n0.2*(1/365)^0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01046848\n```\n\n\n:::\n:::\n\n\n\nFinally: $\\Delta S = 0.0004383562 S + 0.01046848 S \\epsilon$. The 100 simulated 6-months paths of the stock price $S$ are:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(10101010)\nfor(j in 1:100) {\n  delta_S <- NULL \n  S <- rep(40, 180) # Now it is 40 for all days, the loop fill this out.\n  epsilon <- NULL \n  for(i in 1:180) {\n    epsilon[i] <- rnorm(1, 0, 1)\n    delta_S[i] <- 0.16 * (1 / 365) * S[i] + 0.2 * ((1 / 365)^0.5) *\n      epsilon[i] * S[i]\n    S[i+1] <- S[i] + delta_S[i]\n    }\n  if (j==1) {\n    plot(S, type = \"l\", ylim = c(30, 60), \n         ylab = expression(paste(S[t])), xlab = \"t (days)\")\n    points(0, 40, pch = 19, col = \"blue\", cex = 3)\n    abline(h = 10, col = \"red\", lwd = 3)\n    }\n  lines(S)\n  }\nabline(h = 32.55, lwd = 2, col = \"red\")\nabline(h = 56.56, lwd = 2, col = \"red\")\nabline(v = 181, lwd = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![A geometric Brownian motion simulation: 100 stock price paths.](03-wiener-processes_files/figure-html/fig-agbms1spp-1.png){#fig-agbms1spp width=672}\n:::\n:::\n\n\n\n\nThe code above can be problematic because we are not collecting all paths in an object. An alternative code is the following. Again, this is similar to example 15.1 in @Hull.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nS0 <- 40\nnDays <- 360\nmu <- 0.16\nsig <- 0.2\nTT <- 0.5\nmean.logST <- log(S0)+(mu - (sig^2 / 2)) * TT\nvariance.logST <- sig^2 * TT\nlower.ST <- exp(mean.logST + qnorm(0.025) * variance.logST^0.5)\nupper.ST <- exp(mean.logST + qnorm(0.975) * variance.logST^0.5)\nset.seed(3)\nnSim <- 1000\nnSteps <- nDays * TT\nSP_sim <- matrix(0, nrow = nSteps + 1, ncol = nSim)\nfor(i in 1:nSim){\n  SVec <- rep(0, nSteps + 1)\n  SVec[1] <- S0\n  for(j in 2:(nSteps + 1)){\n    DeltaS <- mu * SVec[j - 1] * (1 / nDays) + sig * SVec[j - 1] *\n      rnorm(1) * (1 / nDays)^0.5\n    SVec[j] <- SVec[j - 1] + DeltaS\n  }\n  SP_sim[, i] <- SVec\n}\n```\n:::\n\n\n\n\nNow, let's plot the results.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatplot(0:nSteps, SP_sim, type = 'l', col = rgb(0, 0, 1 ,0.3), lty = 1,\n        ylab = expression(paste(S[t])),\n        xlab = \"Time\")\npoints(0, S0, pch = 19, cex = 3)\nabline(h = lower.ST)\nabline(h = upper.ST)\nabline(v = nSteps)\n```\n\n::: {.cell-output-display}\n![A geometric Brownian motion simulation: 1000 stock price paths.](03-wiener-processes_files/figure-html/fig-agbms1spp2-1.png){#fig-agbms1spp2 width=672}\n:::\n:::\n\n\n\n\nLet's verify that there is approximately a 95% probability that the stock price in 6 months will lie between the lower and upper bounds shown above.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - (sum(SP_sim[nSteps + 1, ] < lower.ST) + \n       sum(SP_sim[nSteps + 1, ] > upper.ST)) / 1000\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.967\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nS0 <- 40\nmu <- 0.16\nsig <- 0.2\nTT <- 0.5\nmean.logST <- log(S0)+(mu - (sig^2 / 2)) * TT\nvariance.logST <- sig^2 * TT\nlower.ST <- exp(mean.logST + qnorm(0.025) * variance.logST^0.5)\nupper.ST <- exp(mean.logST + qnorm(0.975) * variance.logST^0.5)\nlower.ST\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32.51491\n```\n\n\n:::\n\n```{.r .cell-code}\nupper.ST\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 56.6029\n```\n\n\n:::\n:::\n\n\n\n\nNice.\n\nThis is how a stock price evolves according to the Black-Scholes formula.\n\n",
    "supporting": [
      "03-wiener-processes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/vembedr-0.1.5/css/vembedr.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}