{
  "hash": "77ae47a0caee420834786139e0b5c949",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n\n# Value at risk\n\nValue at Risk (VaR) is an attempt to provide a single number summarizing the total risk in a portfolio of financial assets. Here, we develop and extend the example called *Investment in Four Stock Indices* in Chapters 22 and 23 of @Hull. The database used in this example <tt>`dataR.txt`</tt> is available [here](https://github.com/mlozanoqf/tutorial_if/blob/main/dataR.txt).\n\nSuppose that we want to calculate VaR for a portfolio using a one-day time horizon, a 99% confidence level, and 501 days of data, from Monday August 7, 2006 to Thursday September 25, 2008.\n\n## Prepare the data\n\nLoad and prepare the database.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read.table(\"dataR.txt\", sep = \"\", header = TRUE) \n```\n:::\n\n\n\n\nTake a look of the database.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      DJIA FTSE100 USDGBP   CAC40 EURUSD   Nikkei YENUSD\n1 11219.38  5828.8 1.9098 4956.34 0.7776 15154.06 115.00\n2 11173.59  5818.1 1.9072 4967.95 0.7789 15464.66 115.08\n3 11076.18  5860.5 1.9086 5025.15 0.7762 15656.59 115.17\n4 11124.37  5823.4 1.8918 4976.64 0.7828 15630.91 115.41\n5 11088.02  5820.1 1.8970 4985.52 0.7833 15565.02 116.07\n6 11097.87  5870.9 1.8923 5046.93 0.7847 15857.11 116.45\n```\n\n\n:::\n:::\n\n\n\nThese are four international stock indices: Dow Jones Industrial Average (DJIA) in the US, the FTSE 100 in the UK, the CAC 40 in France, and the Nikkei 225 in Japan together with the corresponding exchange rates.\n\nBecause we are considering a US investor in this example, the value of the FTSE 100, CAC 40, and Nikkei 225 must be measured in US dollars. The *adjusted* US dollar equivalent of stock indices are calculated as:\n\n$FTSE_{USD}=FTSE_{GBP}\\times\\frac{USD}{GBP}$.\n\n$CAC_{USD}=\\frac{CAC_{EUR}}{\\frac{EUR}{USD}}$.\n\n$Nikkei_{USD}=\\frac{Nikkei_{JPY}}{\\frac{JPY}{USD}}$.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj <- df %>%\n  mutate(Day = c(0:501)) %>%\n  mutate(AFTSE100 = FTSE100 * USDGBP) %>%\n  mutate(ACAC40 = CAC40 / EURUSD) %>%\n  mutate(ANikkei = Nikkei / YENUSD)\n```\n:::\n\n\n\n\nThe following is the US dollar equivalent of stock indices for historical simulation. This is the same as @Hull, Table 22.2:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj %>%\n  select(Day, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  slice(1, 2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Day     DJIA  AFTSE100   ACAC40  ANikkei\n1   0 11219.38 11131.842 6373.894 131.7744\n2   1 11173.59 11096.280 6378.162 134.3818\n3   2 11076.18 11185.350 6474.040 135.9433\n4   3 11124.37 11016.708 6357.486 135.4381\n5 499 10825.17  9438.580 6033.935 114.2604\n6 500 11022.06  9599.898 6200.396 112.8221\n```\n\n\n:::\n:::\n\n\n\nThe VaR estimation uses 501 observations because we count from day zero through day 500. The *A* before the index name stands for *adjusted*. A graphical representation of the table above:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj %>%\n  mutate(ANikkei = ANikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  filter(obs < 502) %>%\n  gather(IX, Adj, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(IX = as.factor(IX)) %>%\n  ggplot(aes(x = obs, y = Adj, col = IX)) +\n  geom_line(size = 1) +\n  labs(y = \"US dollar equivalent of stock indices\", x = \"\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Adjusted index values, Nikkei = Nikkei $\\times$ 100.](04-value-at-risk_files/figure-html/fig-aivnn-1.png){#fig-aivnn width=672}\n:::\n:::\n\n\n\nThe time-series starts on Monday August 7, 2006 and ends on Thursday September 25, 2008. These are 501 daily past observations. In the plot below, we also show the value of Friday September 26, 2008 as a dot, this is observation 502 and we call it <tt>`tomorrow`</tt>. This observation 502 is excluded from the VaR estimation because it represents an unknown future value, and it will be useful for us to evaluate our estimations.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntomorrow <- df.Adj %>%\n  mutate(ANikkei = ANikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  filter(obs == 502) %>%\n  gather(IX, Adj, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(IX = as.factor(IX))\n\ndf.Adj %>%\n  mutate(ANikkei = ANikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  filter(obs > 400) %>%\n  filter(obs < 502) %>%\n  gather(IX, Adj, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(IX = as.factor(IX)) %>%\n  ggplot(aes(x = obs, y = Adj, col = IX)) +\n  geom_line(size = 1) +\n  geom_point(aes(obs, Adj), size = 2, alpha = 0.4, data = tomorrow) +\n  labs(y = \"US dollar equivalent of stock indices\", x = \"\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Adjusted index values, Nikkei = Nikkei $\\times$ 100, zoom view.](04-value-at-risk_files/figure-html/fig-aivnnzv-1.png){#fig-aivnnzv width=672}\n:::\n:::\n\n\n\nThe stock indices values of Friday September 26, 2008 are:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntomorrow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obs       IX       Adj\n1 502     DJIA 11143.130\n2 502 AFTSE100  9379.123\n3 502   ACAC40  6081.478\n4 502  ANikkei 11216.788\n```\n\n\n:::\n:::\n\n\n\n\n## Historical simulation\n\nThe historical simulation method requires scenarios of the possible stock indices values for Friday September 26, 2008. In particular, we constructed 500 scenarios for Friday September 26, 2008 with 501 past observations. The historical simulation assumes that the stock index value of Friday September 26 2008 depends on the value of Thursday September 25 2008 times a percentage change (which could be positive or negative). The percentage changes are calculated as follows. The first percentage change is from Monday August 7 2006 to Tuesday August 8 2006. The second percentage change is from Tuesday August 8 2006 to Wednesday August 9 2006, and so on. In sum, we assume that tomorrow may behave as the past 500 days.\n\nTake the adjusted values as a reference:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj %>%\n  select(Day, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  slice(1, 2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Day     DJIA  AFTSE100   ACAC40  ANikkei\n1   0 11219.38 11131.842 6373.894 131.7744\n2   1 11173.59 11096.280 6378.162 134.3818\n3   2 11076.18 11185.350 6474.040 135.9433\n4   3 11124.37 11016.708 6357.486 135.4381\n5 499 10825.17  9438.580 6033.935 114.2604\n6 500 11022.06  9599.898 6200.396 112.8221\n```\n\n\n:::\n:::\n\n\n\nThe first three Dow Jones scenarios $SDJIA$ are: \n\n$SDJIA_1 = 11022.06 \\times \\frac{11173.59}{11219.38} \\rightarrow SDJIA_1 = 10977.08$.\n\n$SDJIA_2 = 11022.06 \\times \\frac{11076.18}{11173.59} \\rightarrow SDJIA_2 = 10925.97$\n\n$SDJIA_3 = 11022.06 \\times \\frac{11124.37}{11076.18} \\rightarrow SDJIA_3 = 11070.01$\n\nThe three Dow Jones possible values according to the historical approach for September 26, 2008 are: 10977.08, 10925.97 and 11070.01. We know the actual value is 11143.130, but this is only for evaluation purposes.\n\nScenarios generated for September 26, 2008:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj.S <- df.Adj %>%\n  mutate(obs = c(0:501)) %>%\n  mutate(SDJIA = DJIA[501] * (DJIA/lag(DJIA))) %>%\n  mutate(SFTSE100 = AFTSE100[501] * (AFTSE100/lag(AFTSE100))) %>%\n  mutate(SCAC40 = ACAC40[501] * (ACAC40/lag(ACAC40))) %>%\n  mutate(SNikkei = ANikkei[501] * (ANikkei/lag(ANikkei)))\n\ndf.Adj.S %>%\n  select(obs, SDJIA, SFTSE100, SCAC40, SNikkei) %>%\n  slice(2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obs    SDJIA SFTSE100   SCAC40  SNikkei\n1   1 10977.08 9569.230 6204.547 115.0545\n2   2 10925.97 9676.957 6293.603 114.1331\n3   3 11070.01 9455.160 6088.768 112.4028\n4 499 10831.43 9383.488 6051.936 113.8498\n5 500 11222.53 9763.974 6371.450 111.4019\n```\n\n\n:::\n:::\n\n\n\n\nThis is similar to Table 22.3, @Hull. Let's see the scenarios above in a plot, including the actual values for September 26, 2008:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(tomorrow$IX) <- list(SCAC40 = \"ACAC40\", SDJIA = \"DJIA\", \n                         SFTSE100 = \"AFTSE100\", SNikkei = \"ANikkei\")\n\ndf.Adj.S %>%\n  mutate(SNikkei = SNikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, SDJIA, SFTSE100, SCAC40, SNikkei) %>%\n  filter(obs < 502) %>%\n  gather(IX, S, SDJIA, SFTSE100, SCAC40, SNikkei) %>%\n  mutate(IX = as.factor(IX)) %>%\n  ggplot(aes(x = IX, fill = IX)) +\n  geom_violin(aes(IX, S), draw_quantiles = 0.5) +\n  geom_point(aes(IX, Adj), size = 3,\n             data = tomorrow, show.legend = FALSE) +\n  labs(y = \"Scenarios generated for September 26, 2008\", x = \"\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](04-value-at-risk_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nAccording to the example, an investor in the United States owns, on September 25, 2008, a portfolio worth \\$10 million consisting of 40% in the DJIA, 30% in the FTSE, 10% in the CAC, and 20% in the Nikkei. We can calculate the correspondent 500 scenarios of the possible portfolio value $p$ for September 26, 2008:\n\n$p_1 = 4000 \\frac{SDJIA_1}{DJIA_{sept.25.2008}} + 3000 \\frac{SFTSE_1}{FTSE_{sept.25.2008}} + 1000 \\frac{SCAC_1}{CAC_{sept.25.2008}} + 2000  \\frac{SNikkei_1}{Nikkei_{sept.25.2008}}$,\n\n$p_1 = 4000 \\frac{10977.08}{11022.06} + 3000 \\frac{9569.230}{9599.898} + 1000 \\frac{6204.547}{6200.396} + 2000  \\frac{115.0545}{112.8221}$,\n\n$p_1 = \\$10,014.334$.\n\n$p_2 = 4000 \\frac{SDJIA_2}{DJIA_{sept.25.2008}} + 3000 \\frac{SFTSE_2}{FTSE_{sept.25.2008}} + 1000 \\frac{SCAC_2}{CAC_{sept.25.2008}} + 2000  \\frac{SNikkei_2}{Nikkei_{sept.25.2008}}$,\n\n$p_2 = 4000 \\frac{10925.97}{11022.06} + 3000 \\frac{9676.957}{9599.898} + 1000 \\frac{6293.603}{6200.396} + 2000  \\frac{114.1331}{112.8221}$,\n\n$p_2 = \\$10,027.481$.\n\nAnd so on.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj.S <- df.Adj.S %>%\n  mutate(p = (4000 * SDJIA / DJIA[501]) + # Investment portfolio value\n             (3000 * SFTSE100 / AFTSE100[501]) + \n             (1000 * SCAC40 / ACAC40[501]) + \n             (2000 * SNikkei / ANikkei[501])) %>%\n  mutate(l = 10000 - p) # Losses l\n\ndf.Adj.S %>%\n  select(obs, SDJIA, SFTSE100, SCAC40, SNikkei, p, l) %>%\n  slice(2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obs    SDJIA SFTSE100   SCAC40  SNikkei         p          l\n1   1 10977.08 9569.230 6204.547 115.0545 10014.334  -14.33385\n2   2 10925.97 9676.957 6293.603 114.1331 10027.481  -27.48131\n3   3 11070.01 9455.160 6088.768 112.4028  9946.736   53.26406\n4 499 10831.43 9383.488 6051.936 113.8498  9857.465  142.53549\n5 500 11222.53 9763.974 6371.450 111.4019 10126.439 -126.43897\n```\n\n\n:::\n:::\n\n\n\n\nThe $l$ stands for portfolio losses, it is $l = \\$10,000 - p$. Note that a negative loss represents a portfolio gain. Values above are exactly the same as in @Hull Table 22.3.\n\nVisually.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl <- df.Adj.S %>%\n  mutate(obs = c(0:501)) %>%\n  select(obs, l) %>%\n  filter(obs > 0 & obs < 501) %>%\n  select(l) %>%\n  unlist()\n\nl.tomorrow <- df.Adj.S %>%\n  mutate(obs = c(0:501)) %>%\n  select(obs, l) %>%\n  filter(obs == 501) %>%\n  select(l) %>%\n  unlist()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l, type = \"h\", lwd = 2, \n     xlab = \"500 scenarios (sorted by historical date)\",\n     ylab = \"Portfolio gains (-) and losses (+)\", \n     col = ifelse(l < 0, \"blue\", \"red\"))\npoints(501, l.tomorrow, pch = 19, cex = 2)\nabline(0, 0)\nabline(v = 0)\nlines(seq(0, max(l, na.rm = TRUE), length.out = 500), lty = 2)\nlines(seq(0, min(l, na.rm = TRUE), length.out = 500), lty = 2)\nabline(h = 253.385, lwd = 2, col = \"green\")\nlegend(\"bottomleft\", legend = c(\"Gains\", \"Losses\", \"Historic VaR: 253.385\"),\n       col = c(\"blue\", \"red\", \"green\"), lty = 1, bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Today is September 25, 2008. What is the worst that can happen to my portfolio tomorrow?](04-value-at-risk_files/figure-html/fig-tis22witwtchtmpt-1.png){#fig-tis22witwtchtmpt width=672}\n:::\n:::\n\n\n\n\nNow, a histogram of losses.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(l, 15, xlab = \"Portfolio losses (+) and gains (-)\", main = NULL)\npoints(l.tomorrow, 1, pch = 19, cex = 2)\nabline(v = 253.385, col = \"red\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Historic VaR: 253.385\"), col = \"red\", \n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Histogram of losses for the scenarios considered between September 25 and 26, 2008: a histogram.](04-value-at-risk_files/figure-html/fig-holftscbs2a22ah-1.png){#fig-holftscbs2a22ah width=672}\n:::\n:::\n\n\n\n\nThe point refers to what really happened, and the red line is the VaR following a historic approach. Now, the same information but now using a density plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndensi <- density(l, na.rm = TRUE)\nplot(densi, main = \"\", xlab = \"Portfolio losses (+) and gains (-)\")\npolygon(densi, col = \"grey\", border = \"black\")\npoints(l.tomorrow, 0, pch = 19, cex = 2)\nabline(v = 253.385, col = \"red\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Historic VaR: 253.385\"), col = \"red\", \n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Histogram of losses for the scenarios considered between September 25 and 26, 2008: a density plot.](04-value-at-risk_files/figure-html/fig-holftscbs2a22adp-1.png){#fig-holftscbs2a22adp width=672}\n:::\n:::\n\n\n\n\nHere is a histogram that looks like the one in @Hull.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(l, 15, axes = F, lty = \"blank\", col = \"grey\", main = \"\",\n     xlab = \"Portfolio losses (+) and gains (-)\")\naxis(1, pos = 0)\naxis(2, pos = 0, las = 1)\n```\n\n::: {.cell-output-display}\n![Figure 22.3. Histogram of losses for the scenarios considered between September 25 and 26, 2008.](04-value-at-risk_files/figure-html/fig-f2holftscbs2a22-1.png){#fig-f2holftscbs2a22 width=672}\n:::\n:::\n\n\n\n\nA table for the losses ranked. In particular, losses ranked from highest to lowest for 500 scenarios (first 15 values).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTable22.4 <- data.frame(scenario.number = order(l, decreasing = TRUE),\n                        `loss in positive values` = \n                          l[order(l, decreasing = TRUE)])\nhead(Table22.4, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     scenario.number loss.in.positive.values\nl494             494                477.8410\nl339             339                345.4351\nl349             349                282.2038\nl329             329                277.0413\nl487             487                253.3850\nl227             227                217.9740\nl131             131                202.2555\nl238             238                201.3892\nl473             473                191.2691\nl306             306                191.0497\nl477             477                185.1269\nl495             495                184.4496\nl376             376                182.7072\nl237             237                180.1048\nl365             365                172.2237\n```\n\n\n:::\n:::\n\n\n\n\nAnd the last values (not shown in Hull).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(Table22.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     scenario.number loss.in.positive.values\nl395             395               -224.5146\nl489             489               -284.9247\nl341             341               -307.9301\nl377             377               -316.4893\nl379             379               -333.0218\nl497             497               -555.7954\n```\n\n\n:::\n:::\n\n\n\n\nNote that one of the highest gains happens in scenario 497, almost at the end.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR.hist <- 253.3850\t\nResults <- data.frame(VaR.method = \"Historical simulation, sub-optimal weights\", \n                      VaR = VaR.hist)\nResults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  VaR.method     VaR\n1 Historical simulation, sub-optimal weights 253.385\n```\n\n\n:::\n:::\n\n\n\n\nWe call sub-optimal weights because the allocation of 40% in the DJIA, 30% in the FTSE, 10% in the CAC, and 20% in the Nikkei is arbitrary. The VaR according to the historic approach is the highest 5th loss because the top 1% of 500 scenarios is the 5th scenario. We can view this in a barplot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(l[order(l, decreasing = TRUE)], \n        names.arg = order(l, decreasing = TRUE), ylim = c(0, 500), \n        xlim = c(0, 20), las = 2, cex.names = 1, ylab = \"Portfolio loss ($000s)\",\n        col = \"red\", xlab = \"Scenario number (ranked)\")\nabline(h = 253.385, lwd = 3)\nabline(h = 0, lwd = 3)\nabline(h = l.tomorrow, lwd = 3, col = \"green\")\nlegend(\"topright\", legend = c(\"Historic VaR: 253.385\", \n       \"What really happened\"), col = c(\"black\", \"green\"), \n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Extract of Table 22.4 in a graph: 1 percent historical VaR 253.385, realized loss in green.](04-value-at-risk_files/figure-html/fig-eot2iagvha1p2wrhig-1.png){#fig-eot2iagvha1p2wrhig width=672}\n:::\n:::\n\n\n\n\nThe top 1% can also be explored with the <tt>`quantile()`</tt> function. R's default quantile estimator interpolates between order statistics, so its 99% value differs from Hull's fifth-worst-scenario historical VaR.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR.hist.quantile <- quantile(l, 0.99)\nVaR.hist.quantile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     99% \n218.3281 \n```\n\n\n:::\n:::\n\n\n\n\nTo reproduce Hull's discrete historical VaR, we can take the fifth largest loss directly:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR.hist.discrete <- sort(l, decreasing = TRUE)[5]\nVaR.hist.discrete\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l487 \n253.385 \n```\n\n\n:::\n:::\n\n\n\n\nIf we use the default <tt>`quantile()`</tt> function at the 99% level we end up with:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(l, 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     99% \n218.3281 \n```\n\n\n:::\n:::\n\n\n\nA graphical approach:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(seq(from = 0.902, to = 1, by = 0.002), \n     quantile(l, seq(from = 0.902, to = 1, by = 0.002)), cex = 1.5,\n     xlab = \"Confidence level (vertical line at 99%)\", \n     ylab = \"Portfolio VaR\")\nabline(v = 0.99, lty = 2, lwd = 2)\nabline(h = quantile(l, 0.99), col = \"blue\", lty = 2, lwd = 2)\nabline(h = Table22.4[5, 2], col = \"red\", lty = 2, lwd = 2)\nlegend(\"topleft\", legend = c(\"99% level\", \"Historic VaR: 253.385\", \n                             \"99% quantile VaR: 218.3281\"),\n       col = c(\"black\", \"red\", \"blue\"), lty = 2, bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![A quantile approach.](04-value-at-risk_files/figure-html/fig-aqa-1.png){#fig-aqa width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nci <- seq(0, 1, length.out = 500)\nind <- c(1:500)\ntail(data.frame(\"quantile function\" = quantile(l, ci), \n                \"scenario number\" = order(l),\n                \"sort losses\" = sort(l)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             quantile.function scenario.number sort.losses\n98.9979960%           217.9740             227    217.9740\n99.1983968%           253.3850             487    253.3850\n99.3987976%           277.0413             329    277.0413\n99.5991984%           282.2038             349    282.2038\n99.7995992%           345.4351             339    345.4351\n100.0000000%          477.8410             494    477.8410\n```\n\n\n:::\n:::\n\n\n\n\nSummary of results.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results %>%\n  add_row(VaR.method = \n            \"Historical approximate quantile(), sub-optimal weights\", \n          VaR = VaR.hist.quantile) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                              VaR.method      VaR\n1 Historical approximate quantile(), sub-optimal weights 218.3281\n2             Historical simulation, sub-optimal weights 253.3850\n```\n\n\n:::\n:::\n\n\n\n\n## Model building approach\n\nThe drawback of this method is that it assumes a normal distribution and we know $l$ is not normal. The advantage of this method is its simplicity. \nTransform adjusted indices to returns.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR <- df.Adj %>%\n  select(Day, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(RDJIA = (DJIA-lag(DJIA))/lag(DJIA)) %>%\n  mutate(RFTSE100 = (AFTSE100-lag(AFTSE100))/lag(AFTSE100)) %>%\n  mutate(RCAC40 = (ACAC40-lag(ACAC40))/lag(ACAC40)) %>%\n  mutate(Nikkei = (ANikkei-lag(ANikkei))/lag(ANikkei)) %>%\n  select(RDJIA, RFTSE100, RCAC40, Nikkei) %>%\n  slice(-1)\n\nR.tomorrow <- R %>%\n  slice(501)\n\nR <- R %>%\n  slice(-501)\n```\n:::\n\n\n\n\nReplicate Hull's table 23.5. This is the correlation matrix on September 25, 2008, calculated by giving equal weight to the last 500 daily returns.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRcor <- cor(R)\nTable23.5 <- Rcor\nTable23.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               RDJIA  RFTSE100    RCAC40      Nikkei\nRDJIA     1.00000000 0.4891059 0.4957096 -0.06189921\nRFTSE100  0.48910594 1.0000000 0.9181083  0.20094221\nRCAC40    0.49570963 0.9181083 1.0000000  0.21095096\nNikkei   -0.06189921 0.2009422 0.2109510  1.00000000\n```\n\n\n:::\n:::\n\n\n\n\nReplicate Hull's table 23.6. This is the covariance matrix on September 25, 2008, calculated by giving equal weight to the last 500 daily returns.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRcov <- cov(R)\nTable23.6 <- Rcov\nTable23.6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 RDJIA     RFTSE100       RCAC40        Nikkei\nRDJIA     1.229524e-04 7.696591e-05 7.682514e-05 -9.493488e-06\nRFTSE100  7.696591e-05 2.013973e-04 1.821076e-04  3.944302e-05\nRCAC40    7.682514e-05 1.821076e-04 1.953506e-04  4.078130e-05\nNikkei   -9.493488e-06 3.944302e-05 4.078130e-05  1.913129e-04\n```\n\n\n:::\n:::\n\n\n\n\nThis covariance matrix is quite similar to the one in @Hull. We are not taking round values this explains minor differences.\n\nThe variance of the portfolio losses ($000s) is:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRsd <- apply(R, 2, sd)\nalpha <- c(4000, 3000, 1000, 2000)\n(Pvar <- t(alpha) %*% Rcov %*% alpha) # equation in page 506 (chapter 22)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 8779.392\n```\n\n\n:::\n:::\n\n\n\n\nThis is slightly different as in @Hull: 8,761.833. The standard deviation is the square root of this:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Psd <- Pvar^0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 93.69841\n```\n\n\n:::\n:::\n\n\n\n\nAs expected, this is a bit different as in @Hull (93.60). The one-day 99% VaR in is therefore:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(VaR.ew <- qnorm(0.99, 0, 1) * Psd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 217.9751\n```\n\n\n:::\n:::\n\n\n\n\nIn @Hull, this value is \\$217,757, which compares with \\$253,385, calculated using the historical simulation approach.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \n            \"Model building equally weighted, sub-optimal weights\", \n          VaR = VaR.ew) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                              VaR.method      VaR\n1 Historical approximate quantile(), sub-optimal weights 218.3281\n2             Historical simulation, sub-optimal weights 253.3850\n3   Model building equally weighted, sub-optimal weights 217.9751\n```\n\n\n:::\n:::\n\n\n\n\nWe are interested to compare the equally weighted approach with the EWMA (exponentially weighted moving average method).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model building example -- EWMA\ncovEWMA <-\n  function(factors, lambda = 0.96, return.cor = FALSE) {\n    factor.names  = colnames(factors)\n    t.factor      = nrow(factors)\n    k.factor      = ncol(factors)\n    factors       = as.matrix(factors)\n    t.names       = rownames(factors)\n    factor.means  = colMeans(factors)\n\n    cov.f.ewma = array(,c(t.factor, k.factor, k.factor))\n    cov.f = var(factors)  # unconditional variance as EWMA at time = 0\n    FF = (factors[1, ] - factor.means) %*% t(factors[1,] - factor.means)\n    cov.f.ewma[1,,] = (1 - lambda) * FF  + lambda * cov.f\n    for (i in 2:t.factor) {\n    FF = (factors[i, ] - factor.means) %*% t(factors[i, ] - factor.means)\n    cov.f.ewma[i,,] = (1 - lambda) * FF  + lambda * cov.f.ewma[(i-1),,]\n    }\n    dimnames(cov.f.ewma) = list(t.names, factor.names, factor.names)\n\n    if(return.cor) {\n      cor.f.ewma = cov.f.ewma\n      for (i in 1:dim(cor.f.ewma)[1]) {\n        cor.f.ewma[i, , ] = cov2cor(cov.f.ewma[i, ,])\n      }\n      return(cor.f.ewma)\n    } else {\n      return(cov.f.ewma)\n    }\n  }\n```\n:::\n\n\n\n\nLet's implement this approach to our problem. Covariance matrix on September 25, 2008, calculated using the EWMA method with $\\lambda=0.94$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRdf <- as.data.frame(R)\nC <- covEWMA(Rdf, lambda = 0.94)[500,,] \nTable23.7 <- C\nTable23.7\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 RDJIA     RFTSE100       RCAC40        Nikkei\nRDJIA     0.0004801472 0.0004300030 0.0004257243 -0.0000398876\nRFTSE100  0.0004300030 0.0010311334 0.0009630006  0.0002090981\nRCAC40    0.0004257243 0.0009630006 0.0009535706  0.0001681154\nNikkei   -0.0000398876 0.0002090981 0.0001681154  0.0002534478\n```\n\n\n:::\n:::\n\n\n\n\nThe variance of portfolio losses is:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Pvar_EWMA <- t(alpha) %*% C %*% alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 40977.22\n```\n\n\n:::\n:::\n\n\n\n\nIn @Hull, this value is 40,995.765. The standard deviation is the square root of this, or:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Psd_EWMA <- Pvar_EWMA^0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 202.4283\n```\n\n\n:::\n:::\n\n\n\n\nIn @Hull, this value is 202.474. The one-day 99% VaR is therefore:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(VaR.ewma <- qnorm(0.99, 0, 1) * Psd_EWMA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 470.9187\n```\n\n\n:::\n:::\n\n\n\n\nIn @Hull, this value is 471,025, over twice as high as the value given when returns are equally weighted.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \"Model building EWMA, sub-optimal weights\", \n          VaR = VaR.ewma) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                              VaR.method      VaR\n1 Historical approximate quantile(), sub-optimal weights 218.3281\n2             Historical simulation, sub-optimal weights 253.3850\n3               Model building EWMA, sub-optimal weights 470.9187\n4   Model building equally weighted, sub-optimal weights 217.9751\n```\n\n\n:::\n:::\n\n\n\n\nLet's replicate Table 23.8. Volatilities (% per day) using equal weighting and EWMA.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTable23.8 <- data.frame(Rsd * 100, diag(C)^0.5 * 100)\ncolnames(Table23.8) <- c(\"Equal weighting\", \"EWMA\")\nrownames(Table23.8) <- c(\"DJIA\", \"FTSE 100\", \"CAC 40\", \"Nikkei 225\")\nt(Table23.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    DJIA FTSE 100   CAC 40 Nikkei 225\nEqual weighting 1.108839 1.419145 1.397679   1.383159\nEWMA            2.191226 3.211127 3.087994   1.592004\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated daily standard deviations are much higher when EWMA is used than when data are equally weighted. This is because volatilities were much higher during the period immediately preceding September 25, 2008, than during the rest of the 500 days covered by the data.\n\n\n\n\n\n\n\n\n\nThe estimated daily standard deviations are much higher when EWMA is used than when data are equally weighted. This is because volatilities were much higher during the period immediately preceding September 25, 2008, than during the rest of the 500 days covered by the data.\n\n## Optimal allocation\n\nThe current sub-optimal portfolio weights are:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_hull <- alpha / 10000\nW_hullt <- data.frame(W_hull)\nrownames(W_hullt) <- c(\"DJIA\", \"FTSE 100\", \"CAC 40\", \"Nikkei 225\")\nt(W_hullt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       DJIA FTSE 100 CAC 40 Nikkei 225\nW_hull  0.4      0.3    0.1        0.2\n```\n\n\n:::\n:::\n\n\n\n\nLet's calculate optimal weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR <- R * 100\nR.tomorrow <- R.tomorrow * 100\nstocks<- c(\"DJIA\", \"FTSE100\", \"CAC40\", \"Nikkei\")\nsigma <- var(R)\nsd <- diag(sigma)^0.5\nE <- colMeans(R)\nE.tomorrow <- colMeans(R.tomorrow)\nones <- abs(E / E)\na <- c(t(ones) %*% solve(sigma) %*% ones)\nb <- c(t(ones) %*% solve(sigma) %*% E)\nc <- c(t(E) %*% solve(sigma) %*% E)\nd <- c(a * c - (b^2))\ng <- c(solve(sigma) %*% (c * ones - b * E) / d)\nh <- c(solve(sigma) %*% (a * E - b * ones) / d)\nER <- seq(from = -0.3, to = 0.3, by = 0.0001)\nS <- ER\nW <- matrix(0, nrow = length(ER), ncol = length(stocks))\nfor(i in 1:length(ER)){\n  W[i,] <- g + h * ER[i]\n  ER[i] <- W[i,] %*% E\n  S[i] <- (t(W[i,]) %*% sigma %*% W[i, ])^0.5\n  }\nW_min <- (solve(sigma) %*% ones) / a\nR_min <- c(t(W_min) %*% E)\nR_min.realized <- c(t(W_min) %*% E.tomorrow)\nS_min <- c(t(W_min) %*% sigma %*% W_min)^0.5\n# Allocation to mimic the return of the CAC40 but with lower risk\nW.cac40 <- g + h * E[3]\nR_cac40 <- c(t(W.cac40) %*% E)\nR_cac40.realized <- c(t(W.cac40) %*% E.tomorrow)\nS_cac40 <- c(t(W.cac40) %*% sigma %*% W.cac40)^0.5\nR_hull.realized = c(t(W_hull) %*% E.tomorrow)\n```\n:::\n\n\n\n\nNow we have four different portfolio weights alternatives. Two of them are optimal. *Can we reduce the VaR by using optimal weights?*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW <- data.frame(W_hull, W_min, W.cac40, c(0.25, 0.25, 0.25, 0.25))\nrownames(W) <- c(\"DJIA\", \"FTSE 100\", \"CAC 40\", \"Nikkei 225\")\ncolnames(W) <- c(\"Hull, sub-optimal weights\", \n                 \"minimum variance\", \"CAC40 target return\", \n                 \"naive 1/N\")\nt(W)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               DJIA    FTSE 100     CAC 40 Nikkei 225\nHull, sub-optimal weights 0.4000000  0.30000000 0.10000000  0.2000000\nminimum variance          0.5592378  0.03793305 0.02279301  0.3800361\nCAC40 target return       0.6075003 -0.40341894 0.45978629  0.3361323\nnaive 1/N                 0.2500000  0.25000000 0.25000000  0.2500000\n```\n\n\n:::\n:::\n\n\n\n\nIn this @Hull example we assume portfolio weights remains constant. However, we can rebalance portfolio weights. Here, we have the time evolution of minimum variance optimal weights when we consider 5 US industry portfolios as investment assets:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/paH1-bDPsA4\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/paH1-bDPsA4\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nAnd a similar exercise but now with 10 US industry sorted portfolios:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/DyjQbKm-NdE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/DyjQbKm-NdE\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nLet's go back to the main @Hull example and see the results graphically.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_hull <- alpha / 10000\nR_hull <- c(t(W_hull) %*% E)\nS_hull <- c(t(W_hull) %*% sigma %*% W_hull)^0.5\n\nplot(S, ER, type = \"l\", lwd = 3, xlim = c(0.7, 1.6), \n     ylim = c(-0.022, 0.005),\n     ylab = \"Expected return\", xlab = \"Standard deviation\")\npoints(diag(sigma)^0.5, E)\nabline(0, R_hull / S_hull, lty = 3, col = \"blue\")\nabline(0, R_min / S_min, lty = 3, col = \"red\")\npoints(S_min, R_min, col = \"red\", pch = 19, cex = 2)\nabline(0, 0, lty = 3)\ntext(S_min, R_min, \"Minimum\n     variance\", pos = 2, cex = 0.8)\ntext(sd, E, stocks, adj = -0.5, cex = 0.8)\npoints(S_hull, R_hull, col = \"blue\", pch = 19, cex = 2)\ntext(S_hull, R_hull, \"Hull's \n     sub-optimal allocation\", adj = -0.3, cex = 0.8, pos = 1)\nlegend(\"bottomleft\", \n       legend = c(\"DJ=0.4,   FTSE=0.3,     CAC=0.1,     Nikkei=0.2\",\n                            \"DJ=0.56, FTSE=0.038, CAC=0.022, Nikkei=0.38\"),\n       col = c(\"blue\", \"red\"), pch = 19, bg = \"white\", cex = 1)\n```\n\n::: {.cell-output-display}\n![Hull's allocation is sub-optimal, the red one is a better alternative, although with negative expected return.](04-value-at-risk_files/figure-html/fig-haistroiabaawner-1.png){#fig-haistroiabaawner width=672}\n:::\n:::\n\n\n\n\nThe figure suggests that the (optimal) minimum variance alternative reduces the original portfolio risk. In fact, the minimum variance portfolio has a higher return and lower risk. This representation is an estimate of the future. We can evaluate what really happened by using the actual returns.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(R_min.realized <- c(t(W_min) %*% E.tomorrow))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2629549\n```\n\n\n:::\n\n```{.r .cell-code}\n(R_hull.realized = c(t(W_hull) %*% E.tomorrow))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5583249\n```\n\n\n:::\n:::\n\n\n\n\nThis is interesting as it suggests that the sub-optimal allocation would lead to a realized return on Friday September 26, 2008 of -0.5583249%. On the other hand, following the optimal minimum variance allocation would lead to a portfolio gain of 0.2629549%. Hull's sub-optimal portfolio allocation turns out to be problematic.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_hull <- alpha / 10000\nR_hull <- c(t(W_hull) %*% E)\nS_hull <- c(t(W_hull) %*% sigma %*% W_hull)^0.5\n\nW_1N <- c(0.25,0.25,0.25,0.25)\nR_1N <- c(t(W_1N) %*% E)\nS_1N <- c(t(W_1N) %*% sigma %*% W_1N)^0.5\n\nplot(S, ER, type = \"l\", lwd = 3, xlim = c(0.7, 1.6), \n     ylim = c(-0.022, 0.005),\n     ylab = \"Expected return\", xlab = \"Standard deviation\")\npoints(diag(sigma)^0.5, E)\nabline(0, R_hull / S_hull, lty = 3, col = \"blue\")\nabline(0, R_min / S_min, lty = 3, col = \"red\")\nabline(0, R_1N / S_1N, lty = 3, col = \"purple\")\npoints(S_min, R_min, col = \"red\", pch = 19, cex = 2)\npoints(S_1N, R_1N, col = \"purple\", pch = 19, cex = 2)\nabline(0, 0, lty = 3)\ntext(S_min, R_min, \"Minimum\n     variance\", pos = 2, cex = 0.8)\ntext(sd, E, stocks, adj = -0.5, cex = 0.8)\npoints(S_hull, R_hull, col = \"blue\", pch = 19, cex = 2)\ntext(S_hull, R_hull, \"Hull's\n     sub-optimal allocation\", adj = -0.3, cex = 0.8, pos = 1)\ntext(S_1N, R_1N, \"1/N alpha\", adj = -0.3, cex = 0.8, pos = 3)\nlegend(\"bottomleft\",\n       legend = \n         c(\"Hull:    DJ=0.4,   FTSE=0.3,     CAC=0.1,     Nikkei=0.2\",\n\"Minvar: DJ=0.56, FTSE=0.038, CAC=0.022, Nikkei=0.38\",\n\"1/N:      DJ=0.25,  FTSE=0.25,  CAC=0.25,  Nikkei=0.25\"),\n       col = c(\"blue\",\"red\", \"purple\"), pch = 19, \nbg = \"white\", cex = 0.9)\n```\n\n::: {.cell-output-display}\n![Hull's allocation is sub-optimal, the red one is a better alternative, although with negative expected return.](04-value-at-risk_files/figure-html/fig-haistroiabaawner2-1.png){#fig-haistroiabaawner2 width=672}\n:::\n:::\n\n\n\n\nThis @Hull example is static. If we consider a dynamic approach, then optimal portfolio weights may change as new data is available. As a result, we end up with different mean-variance frontiers. This is the time evolution of the US efficient frontier assuming 5 industry sorted portfolio as investment assets:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/Fq4UlUCneyI\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/Fq4UlUCneyI\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nIn general, as we increase the number of investment assets, the mean-variance frontier expands. Here is the case of 10 versus 12 US industry sorted portfolios as investment assets:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/_GnJRviyYJI\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/_GnJRviyYJI\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nWe can simulate 10,000 possible values for Friday September 26, 2008 given the mean and standard deviation estimates. The following histograms are generated as in this video:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/P1Ky6-a8DE0\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/P1Ky6-a8DE0\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nFirst, the minimum variance portfolio:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nM <- rnorm(10000, R_min, S_min)\nhist(M, 100, xlim = c(-4, 4), ylim = c(0, 450), main = \"\")\nabline(v = R_min.realized, col = \"blue\", lwd = 3)\nabline(v = quantile(M, 0.025), lty = 2)\nabline(v = quantile(M, 0.975), lty = 2)\n```\n\n::: {.cell-output-display}\n![Minimum variance recommendation and realized outcome in blue.](04-value-at-risk_files/figure-html/fig-mvraroib-1.png){#fig-mvraroib width=672}\n:::\n:::\n\n\n\nThen, the sub-optimal allocation:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nH = rnorm(10000, R_hull, S_hull)\nhist(H, 100, xlim = c(-4, 4), ylim = c(0, 450), main = \"\")\nabline(v = R_hull.realized, col = \"blue\", lwd = 3)\nabline(v = quantile(H, 0.025), lty = 2)\nabline(v = quantile(H, 0.975), lty = 2)\n```\n\n::: {.cell-output-display}\n![Hull sub-optimal recommendation and realized outcome.](04-value-at-risk_files/figure-html/fig-hsoraro-1.png){#fig-hsoraro width=672}\n:::\n:::\n\n\n\nAnd finally, the portfolio that targets the CAC 40 expected return:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nCa <- rnorm(10000, R_cac40, S_cac40)\nhist(Ca, 100, xlim = c(-4, 4), ylim = c(0, 450), main = \"\")\nabline(v = R_cac40.realized, col = \"blue\", lwd = 3)\nabline(v = quantile(Ca, 0.025), lty = 2)\nabline(v = quantile(Ca, 0.975), lty = 2)\n```\n\n::: {.cell-output-display}\n![CAC40 recommendation and realized outcome.](04-value-at-risk_files/figure-html/fig-craro-1.png){#fig-craro width=672}\n:::\n:::\n\n\n\n\nLet's see the portfolio that targets the CAC 40 expected return in a mean-variance plot:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(S, ER, type = \"l\", lwd = 3, xlim = c(0.7, 1.6),\n     ylim = c(-0.022, 0.007), ylab = \"Expected return\",\n     xlab = \"Standard deviation\")\npoints(diag(sigma)^0.5, E)\nabline(0, 0, lty = 3)\npoints(S_cac40, R_cac40, col = \"red\", pch = 19, cex = 2)\npoints(0.68, R_cac40.realized, col = \"red\", pch = 15, cex = 2)\ntext(S_cac40, R_cac40, \"CAC40\n     expected return\", pos = 2, cex = 0.8)\ntext(sd,E,stocks,adj=-0.5,cex=0.8)\nW_hull = alpha / 10000\nR_hull = c(t(W_hull) %*% E)\nS_hull = c(t(W_hull) %*% sigma %*% W_hull)^0.5\npoints(S_hull, R_hull, col = \"blue\", pch = 19, cex = 2)\npoints(0.68, R_hull.realized, col = \"blue\", pch = 15, cex = 2)\nabline(0,R_hull / S_hull, lty = 3, col = \"blue\")\nabline(0,R_cac40 / S_cac40, lty = 3, col = \"red\")\nabline(0,E[3] / sd[3], lty = 3)\nabline(v = S_cac40, lty = 3)\ntext(S_hull, R_hull, \"Hull's\n     sub-optimal allocation\", adj = -0.3, cex = 0.8, pos = 1)\nlegend(\"bottomleft\", \n       legend = c(\"DJ=0.4,     FTSE=0.3,      CAC=0.1,     Nikkei=0.2\",\n                          \"DJ=0.607, FTSE=-0.403, CAC=0.459, Nikkei=0.336\"), col = c(\"blue\", \"red\"), \n       pch = 19, bg = \"white\", cex = 0.9)\n```\n\n::: {.cell-output-display}\n![Estimation of a new optimal alpha: Replicate CAC40 ER.](04-value-at-risk_files/figure-html/fig-eoanoarce-1.png){#fig-eoanoarce width=672}\n:::\n:::\n\n\n\nThese are the realized returns on Friday September 26, 2008.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(R_min.realized)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2629549\n```\n\n\n:::\n\n```{.r .cell-code}\n(R_hull.realized)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5583249\n```\n\n\n:::\n\n```{.r .cell-code}\n(R_cac40.realized)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5183212\n```\n\n\n:::\n:::\n\n\n\n\nAs stated before, Hull's sub-optimal portfolio allocation turns out to be problematic. His recommendation would lead to a return of -0.558%, equivalent to a loss of 0.558%. The optimal minimum variance allocation would lead to a positive return of 0.2629%, and the optimal portfolio that targets the CAC 40 expected return leads to an even higher return of 0.518%.\n\n## Model building approach with optimal weights\n\nNow that we have two additional optimal portfolios, we can compute the corresponding VaR for the model building approach. First, the equally weighted case.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model building approach, equally weighted.\nalpha2 <- c(W_min * 10000)\nalpha3 <- c(W.cac40 * 10000)\n# This is the minimum variance optimal portfolio.\nPvar2 <- t(alpha2) %*% Rcov %*% alpha2\nPsd2 <- Pvar2^0.5\nVaR.ew.optimal <- qnorm(0.99, 0, 1) * Psd2\n# This is optimal portfolio targeting the CAC 40 expected return.\nPvar3 <- t(alpha3) %*% Rcov %*% alpha3\nPsd3 <- Pvar3^0.5\nVaR.ew.optimal.cac <- qnorm(0.99, 0, 1) * Psd3\n```\n:::\n\n\n\n\nSummary of results:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \n        c(\"Model building equally weighted, minimum variance weights\", \n          \"Model building equally weighted, targeting CAC40\"), \n          VaR = c(VaR.ew.optimal, VaR.ew.optimal.cac)) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                 VaR.method      VaR\n1    Historical approximate quantile(), sub-optimal weights 218.3281\n2                Historical simulation, sub-optimal weights 253.3850\n3                  Model building EWMA, sub-optimal weights 470.9187\n4 Model building equally weighted, minimum variance weights 194.3892\n5      Model building equally weighted, sub-optimal weights 217.9751\n6          Model building equally weighted, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\nSecond, the model building approach with EWMA.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPvar2_EWMA <- t(alpha2) %*% C %*% alpha2\nPsd2_EWMA <- Pvar2_EWMA^0.5\nVaR.ewma.optimal <- qnorm(0.99, 0, 1) * Psd2_EWMA\nVaR.ewma.optimal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 338.3195\n```\n\n\n:::\n\n```{.r .cell-code}\nPvar3_EWMA <- t(alpha3) %*% C %*% alpha3\nPsd3_EWMA <- Pvar3_EWMA^0.5\nVaR.ewma.optimal.cac <- qnorm(0.99, 0, 1) * Psd3_EWMA\nVaR.ewma.optimal.cac\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 348.1888\n```\n\n\n:::\n:::\n\n\n\n\nSummary of results.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \n            c(\"Model building EWMA, minimum variance weights\", \n              \"Model building EWMA, targeting CAC40\"), \n          VaR = c(VaR.ewma.optimal, VaR.ewma.optimal.cac)) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                 VaR.method      VaR\n1    Historical approximate quantile(), sub-optimal weights 218.3281\n2                Historical simulation, sub-optimal weights 253.3850\n3             Model building EWMA, minimum variance weights 338.3195\n4                  Model building EWMA, sub-optimal weights 470.9187\n5                      Model building EWMA, targeting CAC40 348.1888\n6 Model building equally weighted, minimum variance weights 194.3892\n7      Model building equally weighted, sub-optimal weights 217.9751\n8          Model building equally weighted, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\n\n## Historic approach with optimal weights\n\nLet's go back to the historic approach. Now we can incorporate a comparison with the optimal weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj.S <- df.Adj.S %>%\n  mutate(p2 = (alpha2[1] * SDJIA / DJIA[501]) + \n             (alpha2[2] * SFTSE100 / AFTSE100[501]) + \n             (alpha2[3] * SCAC40 / ACAC40[501]) + \n             (alpha2[4] * SNikkei / ANikkei[501])) %>%\n  mutate(l2 = 10000 - p2) %>% # Losses l\n  mutate(p3 = (alpha3[1] * SDJIA / DJIA[501]) + \n             (alpha3[2] * SFTSE100 / AFTSE100[501]) + \n             (alpha3[3] * SCAC40 / ACAC40[501]) + \n             (alpha3[4] * SNikkei / ANikkei[501])) %>%\n  mutate(l3 = 10000 - p3) # Losses l\n```\n:::\n\n\n\n\nCalculate the new portfolio losses for optimal weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl2 <- df.Adj.S %>%\n  filter(obs > 0 & obs < 501) %>%\n  select(l2) %>%\n  unlist()\n\nl2.tomorrow <- df.Adj.S %>%\n  filter(obs == 501) %>%\n  select(l2) %>%\n  unlist()\n\nl3 <- df.Adj.S %>%\n  filter(obs > 0 & obs < 501) %>%\n  select(l3) %>%\n  unlist()\n\nl3.tomorrow <- df.Adj.S %>%\n  filter(obs == 501) %>%\n  select(l3) %>%\n  unlist()\n```\n:::\n\n\n\n\nAs a reference, this is the @Hull original case.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\nylab = \"Portfolio gains (-) and losses (+)\", \ncol = ifelse(l < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l), lty = 2)\nabline(h = min(l), lty = 2)\n```\n\n::: {.cell-output-display}\n![Losses with Hull's suboptimal alpha DJ=0.4, FTSE=0.3, CAC=0.1, Nikkei=0.2.](04-value-at-risk_files/figure-html/fig-lwhsadfcn-1.png){#fig-lwhsadfcn width=672}\n:::\n:::\n\n\n\n\nThe one-day 99% value at risk can be estimated as the fifth-worst loss.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(l)[496]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l487 \n253.385 \n```\n\n\n:::\n:::\n\n\n\n\nNow, let's see the historical approach but with minimum variance optimal weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l2, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\n     ylab = \"Portfolio gains (-) and losses (+)\", \n     col = ifelse(l2 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l2), lty = 2)\nabline(h = min(l2), lty = 2)\n```\n\n::: {.cell-output-display}\n![Losses with optimal alpha DJ=0.56, FTSE=0.038, CAC=0.022, Nikkei=0.38.](04-value-at-risk_files/figure-html/fig-lwhsadfcn2-1.png){#fig-lwhsadfcn2 width=672}\n:::\n:::\n\n\n\n\nSee how the range of losses and gains is now reduced. The one-day 99% value at risk can be estimated as the fifth-worst loss.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(l2)[496]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l2487 \n213.6898 \n```\n\n\n:::\n:::\n\n\n\nLet's update our table of results.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \"Historical simulation, minimum variance weights\", \n          VaR = sort(l2)[496]) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                 VaR.method      VaR\n1    Historical approximate quantile(), sub-optimal weights 218.3281\n2           Historical simulation, minimum variance weights 213.6898\n3                Historical simulation, sub-optimal weights 253.3850\n4             Model building EWMA, minimum variance weights 338.3195\n5                  Model building EWMA, sub-optimal weights 470.9187\n6                      Model building EWMA, targeting CAC40 348.1888\n7 Model building equally weighted, minimum variance weights 194.3892\n8      Model building equally weighted, sub-optimal weights 217.9751\n9          Model building equally weighted, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\n\nAnd this is the optimal portfolio targeting the CAC 40 expected return.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l3, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\n     ylab = \"Portfolio gains (-) and losses (+)\", \n     col = ifelse(l3 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l3), lty = 2)\nabline(h = min(l3), lty = 2)\n```\n\n::: {.cell-output-display}\n![Losses with CAC40 optimal alpha DJ=0.607, FTSE=-0.403, CAC=0.459, Nikkei=0.336.](04-value-at-risk_files/figure-html/fig-lwcoadfcn-1.png){#fig-lwcoadfcn width=672}\n:::\n:::\n\n\n\n\nNote that the range is reduced but allows for a higher gains. Let's see these three together. The one-day 99% value at risk can be estimated as the fifth-worst loss.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(l3)[496]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l3494 \n248.8909 \n```\n\n\n:::\n:::\n\n\n\nLet's update the table of results.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \"Historical simulation, targeting CAC40\", \n          VaR = sort(l3)[496]) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                  VaR.method      VaR\n1     Historical approximate quantile(), sub-optimal weights 218.3281\n2            Historical simulation, minimum variance weights 213.6898\n3                 Historical simulation, sub-optimal weights 253.3850\n4                     Historical simulation, targeting CAC40 248.8909\n5              Model building EWMA, minimum variance weights 338.3195\n6                   Model building EWMA, sub-optimal weights 470.9187\n7                       Model building EWMA, targeting CAC40 348.1888\n8  Model building equally weighted, minimum variance weights 194.3892\n9       Model building equally weighted, sub-optimal weights 217.9751\n10          Model building equally weighted, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\n\nLet's see the three historical approaches together.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1, 3), oma = c(0, 0, 2, 0))\npar(pty = \"s\")\nplot(l, type = \"h\", ylim = c(-600, 600), lwd = 2, xlab = \"\",\n     main = \"Hull original case.\", \n     ylab = \"Portfolio gains (-) and losses (+)\",\n     col = ifelse(l < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l), lty = 2)\nabline(h = min(l), lty = 2)\nplot(l2, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     main = \"Minimum variance.\",\n     xlab = \"500 scenarios sorted by historical date.\", ylab = \"\",\n     col = ifelse(l2 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l2), lty = 2)\nabline(h = min(l2), lty = 2)\nplot(l3, type = \"h\", ylim = c(-600, 600), lwd = 2, xlab = \"\",\n     main = \"Optimal targeting CAC 40.\", ylab = \"\",\n     col = ifelse(l3 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l3), lty = 2)\nabline(h = min(l3), lty = 2)\n```\n\n::: {.cell-output-display}\n![Hull's suboptimal alpha (left); optimal alpha (center); optimal alpha CAC40 (right).](04-value-at-risk_files/figure-html/fig-hsaoaoa-1.png){#fig-hsaoaoa width=672}\n:::\n:::\n\n\n\n\nA quantile comparison.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlq <- quantile(l, c(0.25, 0.5, 0.75))\nlq2 <- quantile(l2, c(0.25, 0.5, 0.75))\nlq3 <- quantile(l3, c(0.25, 0.5, 0.75))\nll <- data.frame(lq, lq2, lq3)\ncolours <- c(\"red\", \"orange\", \"blue\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(as.matrix(t(ll)), beside = TRUE, col = colours, \n        ylim = c(-60, 60), xlab = \"Quantiles\", \n        ylab = \"Portfolio gains (-) and Losses (+)\")\nlegend(\"topleft\", c(\"Hull original\",\"Optimal minvar\",\n                    \"Replicating CAC40 ER\"), cex = 1.3, bty = \"n\",\n       fill = colours)\n```\n\n::: {.cell-output-display}\n![Quantile comparison of losses distribution.](04-value-at-risk_files/figure-html/fig-qcold-1.png){#fig-qcold width=672}\n:::\n:::\n",
    "supporting": [
      "04-value-at-risk_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/vembedr-0.1.5/css/vembedr.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}